version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: cp-zookeeper
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - cp_zookeeper_data:/var/lib/zookeeper/data
    networks:
      - cp-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - cp_kafka_data:/var/lib/kafka/data
    networks:
      - cp-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    hostname: schema-registry
    container_name: cp-schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
    volumes:
      - cp_schema_registry_data:/var/lib/schema-registry
    networks:
      - cp-network

  connect:
    image: local/debezium-connect-avro:2.4
    hostname: connect
    container_name: debezium-connect
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "18083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      # Using Schema Registry for Avro converters
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      PLUGIN_PATH: /kafka/connect

      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_REST_PORT: 8083
    volumes:
      - cp_connect_plugins:/kafka/connect
    networks:
      - cp-network

volumes:
  cp_zookeeper_data:
    name: cp_zookeeper_data
  cp_kafka_data:
    name: cp_kafka_data
  cp_schema_registry_data:
    name: cp_schema_registry_data
  cp_connect_plugins:
    name: cp_connect_plugins

networks:
  cp-network:
    name: cp-network
